// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjgeqiinzruoghunirgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqZ2VxaWluenJ1b2dodW5pcmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzI4MzYsImV4cCI6MjA2NjI0ODgzNn0.rOtXAEdkZfIDZPu95c8RN1O2BXazN4wWCH7sQ4QR1tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);